In [1]:
import pandas as pd
df=pd.read_csv("medical_students_dataset.csv")
df

Student ID   Age  Gender      Height     Weight Blood Type        BMI  \
0              1.0  18.0  Female  161.777924  72.354947          O  27.645835   
1              2.0   NaN    Male  152.069157  47.630941          B        NaN   
2              3.0  32.0  Female  182.537664  55.741083          A  16.729017   
3              NaN  30.0    Male  182.112867  63.332207          B  19.096042   
4              5.0  23.0  Female         NaN  46.234173          O        NaN   
...            ...   ...     ...         ...        ...        ...        ...   
199995         NaN  24.0    Male  176.503260  95.756997          B  30.737254   
199996     99997.0  29.0  Female  163.917675  45.225194        NaN  16.831734   
199997     99998.0  34.0  Female         NaN  99.648914        NaN  33.189303   
199998     99999.0  30.0  Female  156.446944  50.142824          A  20.486823   
199999    100000.0  20.0  Female  153.927409  99.928405          O  42.175189   

        Temperature  Heart Rate  Blood Pressure  Cholesterol Diabetes Smoking  
0               NaN        95.0           109.0        203.0       No     NaN  
1         98.714977        93.0           104.0        163.0       No      No  
2         98.260293        76.0           130.0        216.0      Yes      No  
3         98.839605        99.0           112.0        141.0       No     Yes  
4         98.480008        95.0             NaN        231.0       No      No  
...             ...         ...             ...          ...      ...     ...  
199995    99.170685        65.0           121.0        130.0       No      No  
199996    97.865785        62.0           125.0        198.0       No     Yes  
199997    98.768210        60.0            90.0        154.0      NaN      No  
199998    98.994212        61.0           106.0        225.0       No      No  
199999    98.595817        95.0           133.0        132.0      NaN      No  

[200000 rows x 13 columns]

In [2]:
df.isnull().sum()

Student ID        20000
Age               20000
Gender            20000
Height            20000
Weight            20000
Blood Type        20000
BMI               20000
Temperature       20000
Heart Rate        20000
Blood Pressure    20000
Cholesterol       20000
Diabetes          20000
Smoking           20000
dtype: int64

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   Student ID      180000 non-null  float64
 1   Age             180000 non-null  float64
 2   Gender          180000 non-null  object 
 3   Height          180000 non-null  float64
 4   Weight          180000 non-null  float64
 5   Blood Type      180000 non-null  object 
 6   BMI             180000 non-null  float64
 7   Temperature     180000 non-null  float64
 8   Heart Rate      180000 non-null  float64
 9   Blood Pressure  180000 non-null  float64
 10  Cholesterol     180000 non-null  float64
 11  Diabetes        180000 non-null  object 
 12  Smoking         180000 non-null  object 
dtypes: float64(9), object(4)
memory usage: 19.8+ MB


In [4]:
df.isnull().sum().sum()

np.int64(260000)

In [5]:
df.shape

(200000, 13)

In [6]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(strategy='median')
df['Age']=imputer.fit_transform(df[['Age']])
df['Student ID']=imputer.fit_transform(df[['Student ID']])
df['Height']=imputer.fit_transform(df[['Height']])
df['Weight']=imputer.fit_transform(df[['Weight']])
df['BMI']=imputer.fit_transform(df[['BMI']])
df['Temperature']=imputer.fit_transform(df[['Temperature']])
df['Heart Rate ']=imputer.fit_transform(df[['Heart Rate']])
df['Blood Pressure']=imputer.fit_transform(df[['Blood Pressure']])
df['Cholesterol']=imputer.fit_transform(df[['Cholesterol']])

In [7]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(strategy="most_frequent")
df["Gender"]=imputer.fit_transform(df[["Gender"]]).ravel()
df["Blood Type"]=imputer.fit_transform(df[["Blood Type"]]).ravel()
df["Diabetes"]=imputer.fit_transform(df[['Height']]).ravel()
df["Smoking"]=imputer.fit_transform(df[["Smoking"]]).ravel()
df.isnull().sum()

Student ID            0
Age                   0
Gender                0
Height                0
Weight                0
Blood Type            0
BMI                   0
Temperature           0
Heart Rate        20000
Blood Pressure        0
Cholesterol           0
Diabetes              0
Smoking               0
Heart Rate            0
dtype: int64

In [8]:
df.drop(columns=["Heart Rate"],inplace=True)
df

Student ID   Age  Gender      Height     Weight Blood Type        BMI  \
0              1.0  18.0  Female  161.777924  72.354947          O  27.645835   
1              2.0  26.0    Male  152.069157  47.630941          B  22.671401   
2              3.0  32.0  Female  182.537664  55.741083          A  16.729017   
3          49943.5  30.0    Male  182.112867  63.332207          B  19.096042   
4              5.0  23.0  Female  174.899914  46.234173          O  22.671401   
...            ...   ...     ...         ...        ...        ...        ...   
199995     49943.5  24.0    Male  176.503260  95.756997          B  30.737254   
199996     99997.0  29.0  Female  163.917675  45.225194          B  16.831734   
199997     99998.0  34.0  Female  174.899914  99.648914          B  33.189303   
199998     99999.0  30.0  Female  156.446944  50.142824          A  20.486823   
199999    100000.0  20.0  Female  153.927409  99.928405          O  42.175189   

        Temperature  Blood Pressure  Cholesterol    Diabetes Smoking  \
0         98.599654           109.0        203.0  161.777924      No   
1         98.714977           104.0        163.0  152.069157      No   
2         98.260293           130.0        216.0  182.537664      No   
3         98.839605           112.0        141.0  182.112867     Yes   
4         98.480008           115.0        231.0  174.899914      No   
...             ...             ...          ...         ...     ...   
199995    99.170685           121.0        130.0  176.503260      No   
199996    97.865785           125.0        198.0  163.917675     Yes   
199997    98.768210            90.0        154.0  174.899914      No   
199998    98.994212           106.0        225.0  156.446944      No   
199999    98.595817           133.0        132.0  153.927409      No   

        Heart Rate   
0              95.0  
1              93.0  
2              76.0  
3              99.0  
4              95.0  
...             ...  
199995         65.0  
199996         62.0  
199997         60.0  
199998         61.0  
199999         95.0  

[200000 rows x 13 columns]

In [9]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["Gender"]=le.fit_transform(df["Gender"])
df["Blood Type"]=le.fit_transform(df["Blood Type"])
df["Diabetes"]=le.fit_transform(df["Diabetes"])
df["Smoking"]=le.fit_transform(df["Smoking"])
df

Student ID   Age  Gender      Height     Weight  Blood Type  \
0              1.0  18.0       0  161.777924  72.354947           3   
1              2.0  26.0       1  152.069157  47.630941           2   
2              3.0  32.0       0  182.537664  55.741083           0   
3          49943.5  30.0       1  182.112867  63.332207           2   
4              5.0  23.0       0  174.899914  46.234173           3   
...            ...   ...     ...         ...        ...         ...   
199995     49943.5  24.0       1  176.503260  95.756997           2   
199996     99997.0  29.0       0  163.917675  45.225194           2   
199997     99998.0  34.0       0  174.899914  99.648914           2   
199998     99999.0  30.0       0  156.446944  50.142824           0   
199999    100000.0  20.0       0  153.927409  99.928405           3   

              BMI  Temperature  Blood Pressure  Cholesterol  Diabetes  \
0       27.645835    98.599654           109.0        203.0     23371   
1       22.671401    98.714977           104.0        163.0      4248   
2       16.729017    98.260293           130.0        216.0     64490   
3       19.096042    98.839605           112.0        141.0     63644   
4       22.671401    98.480008           115.0        231.0     49498   
...           ...          ...             ...          ...       ...   
199995  30.737254    99.170685           121.0        130.0     52699   
199996  16.831734    97.865785           125.0        198.0     27572   
199997  33.189303    98.768210            90.0        154.0     49498   
199998  20.486823    98.994212           106.0        225.0     12932   
199999  42.175189    98.595817           133.0        132.0      7848   

        Smoking  Heart Rate   
0             0         95.0  
1             0         93.0  
2             0         76.0  
3             1         99.0  
4             0         95.0  
...         ...          ...  
199995        0         65.0  
199996        1         62.0  
199997        0         60.0  
199998        0         61.0  
199999        0         95.0  

[200000 rows x 13 columns]

In [10]:
x=df.drop(columns=["Smoking"],axis=1)
y=df["Smoking"]
x

Student ID   Age  Gender      Height     Weight  Blood Type  \
0              1.0  18.0       0  161.777924  72.354947           3   
1              2.0  26.0       1  152.069157  47.630941           2   
2              3.0  32.0       0  182.537664  55.741083           0   
3          49943.5  30.0       1  182.112867  63.332207           2   
4              5.0  23.0       0  174.899914  46.234173           3   
...            ...   ...     ...         ...        ...         ...   
199995     49943.5  24.0       1  176.503260  95.756997           2   
199996     99997.0  29.0       0  163.917675  45.225194           2   
199997     99998.0  34.0       0  174.899914  99.648914           2   
199998     99999.0  30.0       0  156.446944  50.142824           0   
199999    100000.0  20.0       0  153.927409  99.928405           3   

              BMI  Temperature  Blood Pressure  Cholesterol  Diabetes  \
0       27.645835    98.599654           109.0        203.0     23371   
1       22.671401    98.714977           104.0        163.0      4248   
2       16.729017    98.260293           130.0        216.0     64490   
3       19.096042    98.839605           112.0        141.0     63644   
4       22.671401    98.480008           115.0        231.0     49498   
...           ...          ...             ...          ...       ...   
199995  30.737254    99.170685           121.0        130.0     52699   
199996  16.831734    97.865785           125.0        198.0     27572   
199997  33.189303    98.768210            90.0        154.0     49498   
199998  20.486823    98.994212           106.0        225.0     12932   
199999  42.175189    98.595817           133.0        132.0      7848   

        Heart Rate   
0              95.0  
1              93.0  
2              76.0  
3              99.0  
4              95.0  
...             ...  
199995         65.0  
199996         62.0  
199997         60.0  
199998         61.0  
199999         95.0  

[200000 rows x 12 columns]

In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)
x

array([[-1.82388466e+00, -1.72848630e+00, -1.10559743e+00, ...,
         5.20937540e-01, -9.63194488e-01,  1.41071332e+00],
       [-1.82384816e+00, -4.18251437e-03,  9.04488351e-01, ...,
        -6.01635076e-01, -1.66844208e+00,  1.22805663e+00],
       [-1.82381166e+00,  1.28904533e+00, -1.10559743e+00, ...,
         8.85773641e-01,  5.53255638e-01, -3.24525227e-01],
       ...,
       [ 1.82596603e+00,  1.72012127e+00, -1.10559743e+00, ...,
        -8.54213915e-01,  3.57457414e-04, -1.78577874e+00],
       [ 1.82600252e+00,  8.57969379e-01, -1.10559743e+00, ...,
         1.13835248e+00, -1.34818009e+00, -1.69445040e+00],
       [ 1.82603902e+00, -1.29741035e+00, -1.10559743e+00, ...,
        -1.47162885e+00, -1.53567571e+00,  1.41071332e+00]],
      shape=(200000, 12))

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=50)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(160000, 12)
(40000, 12)
(160000,)
(40000,)


In [13]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)

In [14]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))



0.816925
[[32677     0]
 [ 7323     0]]
              precision    recall  f1-score   support

           0       0.82      1.00      0.90     32677
           1       0.00      0.00      0.00      7323

    accuracy                           0.82     40000
   macro avg       0.41      0.50      0.45     40000
weighted avg       0.67      0.82      0.73     40000



c:\Users\shree\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\shree\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\shree\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(ave

In [15]:
lr.fit(x_test,y_test)
y_pred=lr.predict(x_test)

In [16]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))


0.816925
[[32677     0]
 [ 7323     0]]
              precision    recall  f1-score   support

           0       0.82      1.00      0.90     32677
           1       0.00      0.00      0.00      7323

    accuracy                           0.82     40000
   macro avg       0.41      0.50      0.45     40000
weighted avg       0.67      0.82      0.73     40000



c:\Users\shree\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\shree\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\shree\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(ave

In [17]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_test,y_test)
y_pred=dt.predict(x_test)

In [18]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.99945
[[32677     0]
 [   22  7301]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     32677
           1       1.00      1.00      1.00      7323

    accuracy                           1.00     40000
   macro avg       1.00      1.00      1.00     40000
weighted avg       1.00      1.00      1.00     40000



In [19]:
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)

In [20]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.7812
[[28042  4635]
 [ 4117  3206]]
              precision    recall  f1-score   support

           0       0.87      0.86      0.87     32677
           1       0.41      0.44      0.42      7323

    accuracy                           0.78     40000
   macro avg       0.64      0.65      0.64     40000
weighted avg       0.79      0.78      0.78     40000



In [21]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)

In [22]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8532
[[32507   170]
 [ 5702  1621]]
              precision    recall  f1-score   support

           0       0.85      0.99      0.92     32677
           1       0.91      0.22      0.36      7323

    accuracy                           0.85     40000
   macro avg       0.88      0.61      0.64     40000
weighted avg       0.86      0.85      0.81     40000



In [23]:
rf.fit(x_test,y_test)
y_pred=rf.predict(x_test)

In [24]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.99945
[[32672     5]
 [   17  7306]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     32677
           1       1.00      1.00      1.00      7323

    accuracy                           1.00     40000
   macro avg       1.00      1.00      1.00     40000
weighted avg       1.00      1.00      1.00     40000



In [25]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)

In [26]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.794525
[[31120  1557]
 [ 6662   661]]
              precision    recall  f1-score   support

           0       0.82      0.95      0.88     32677
           1       0.30      0.09      0.14      7323

    accuracy                           0.79     40000
   macro avg       0.56      0.52      0.51     40000
weighted avg       0.73      0.79      0.75     40000



In [27]:
knn.fit(x_test,y_test)
y_pred=knn.predict(x_test)

In [28]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.83295
[[31950   727]
 [ 5955  1368]]
              precision    recall  f1-score   support

           0       0.84      0.98      0.91     32677
           1       0.65      0.19      0.29      7323

    accuracy                           0.83     40000
   macro avg       0.75      0.58      0.60     40000
weighted avg       0.81      0.83      0.79     40000



In [29]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(x_train,y_train)
y_pred=nb.predict(x_test)

In [30]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.816925
[[32677     0]
 [ 7323     0]]
              precision    recall  f1-score   support

           0       0.82      1.00      0.90     32677
           1       0.00      0.00      0.00      7323

    accuracy                           0.82     40000
   macro avg       0.41      0.50      0.45     40000
weighted avg       0.67      0.82      0.73     40000



c:\Users\shree\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\shree\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\shree\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(ave

In [31]:
nb.fit(x_test,y_test)
y_pred=nb.predict(x_test)

In [32]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.816925
[[32677     0]
 [ 7323     0]]
              precision    recall  f1-score   support

           0       0.82      1.00      0.90     32677
           1       0.00      0.00      0.00      7323

    accuracy                           0.82     40000
   macro avg       0.41      0.50      0.45     40000
weighted avg       0.67      0.82      0.73     40000



c:\Users\shree\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\shree\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\shree\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(ave